# Generated by Django 4.2.1 on 2023-05-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_product'),
    ]

    operations = [
        # migrations.RunSQL("""
        # INSERT INTO store_collection(title) 
        # VALUES ('collection1')
        # ""","""
        # DELETE FROM store_collection where title='collection1'
        # """)
    ]
